### ISSUE TITLE
Use in editor

### ISSUE THREAD

**Issue by romainquellec** [urish/typewiz#15]
Hello ! Nice project.

Is there a way of using this directly in an editor (Atom/Vscode) ? Is so, how ?

Thanks !

**Comment by urish** [comment]
Thank you! Currently not - only from command line (see [typewiz-webpack instructions](https://github.com/urish/typewiz/tree/master/packages/typewiz-webpack#installation) for an example). 

You can create an npm script to apply the types and run it from your editor, but it is not optimal. If anyone wants to take a stab at creating a VSCode (or Atom) plugin, I'm willing to offer my guidance :-)
