### ISSUE TITLE
Avoid emitting 'Function'

### ISSUE THREAD

**Issue by DanielRosenwasser** [urish/typewiz#20]
While 'Function' is very general, it's problematic in some ways because it's not assignable back to types with more general call signatures like `(...args: any[]) => any`.

You can probably take some inspiration from [how dts-gen determines arity for function](https://github.com/Microsoft/dts-gen/blob/c6b9f5b6f3a71346aae1b3bf7b6ea7bd29518ad1/lib/index.ts#L349) to improve things here.

**Comment by urish** [comment]
That's a good point, thank you Daniel!

Another thought I had - perhaps creating a Proxy object and wrapping the function with this Proxy will allow to actually detect the argument types in runtime?

The dts-gen solution sounds easier to start with though.

**Comment by kaminskypavel** [comment]
@DanielRosenwasser great suggestion, i'll have a stab at it

**Comment by DanielRosenwasser** [comment]
Just as a heads up, dts-gen uses a package called [dts-dom](https://github.com/RyanCavanaugh/dts-dom) which is also another handy utility you can use for building up declarations. 😃
