### ISSUE TITLE
Multiple files

### ISSUE THREAD

**Issue by guigaoliveira** [urish/typewiz#28]
Is it possible to use in multiple files (large project)? 
Thanks!

**Comment by urish** [comment]
Yes, check out [typewiz-node](https://www.npmjs.com/package/typewiz-node) for a node.js project, or [typewiz-webpack](https://www.npmjs.com/package/typewiz-webpack) for a frontend project. As I mentioned in the [blog post](https://medium.com/@urish/manual-typing-is-no-fun-introducing-typewiz-58e3e8813f4c), I used typewiz with [firebase-server](https://github.com/urish/firebase-server), as well as one of the internal project's at blackberry, with hundreds of source files.

If you need more guidance, just drop me a line here.
