### ISSUE TITLE
Implement instrumentation as a TypeScript Compiler Transformer

### ISSUE THREAD

**Issue by urish** [urish/typewiz#41]
Compiler transformers introduced in Microsoft/TypeScript#13764, and they seem to allow modifying the AST directly rather than updating the source code. This should improve performance, though, it seems like we will have to rewrite the instrumentor to support that.

Seems like both [awesome-typescript-loader](https://github.com/s-panferov/awesome-typescript-loader) and [ts-loader](https://github.com/TypeStrong/ts-loader#getcustomtransformers-----before-transformerfactory-after-transformerfactory--) have support for custom transformers.

Here are a few example of what a custom transformer looks like ([source](https://github.com/Microsoft/TypeScript/issues/14419#issuecomment-298814505)): 

https://github.com/longlho/ts-transform-system-import
https://github.com/longlho/ts-transform-img
https://github.com/longlho/ts-transform-react-intl
https://github.com/longlho/ts-transform-css-modules-transform

**Comment by MadaraUchiha** [comment]
I thought applying string processing on the files directly was faster? Or am I missing something?

**Comment by urish** [comment]
It is certainly faster for applying the types (you don't have to parse the source code again, etc). But for the instrumentation, if you have a setup where you already use the TypeScript compiler (and it parses all your source files anyway), we can avoid double parsing by modifying the AST directly after the compiler reads the file but before it processes it.
