### ISSUE TITLE
CLI [RFC]

### ISSUE THREAD

**Issue by urish** [urish/typewiz#53]
After trying TypeWiz on several different projects, I find it useful to have a CLI tool that will be able to perform the following tasks:

1. instrument - in case of a custom configuration not supported by one of our plugins. One such example is [rtf.js](https://github.com/tbluemel/rtf.js/commit/0495956933ea77f00a508f76752f10710c8c3c6b) - see @zoehneto's [comment](https://github.com/urish/typewiz/pull/40#issuecomment-375867600) explaining why it is needed.
2. apply-types - for applying the collected types to the source code, e.g. in [typewiz-webpack](https://github.com/urish/typewiz/tree/master/packages/typewiz-webpack#installation)
3. type-coverage - print the percentage of type coverage (can also be used to enforce specific coverage target in CI), see #48 

I am thinking about renaming the core API of typewiz to `typewiz-core`, and then using `typewiz` package to the CLI, so as a user you just install `typewiz` and can use it (most users shouldn't care about the API part too much).

I'd love to hear user thoughts about this!

**Comment by zoehneto** [comment]
Sounds interesting, in terms of the interface you might want to take a look at the istanbul js frontend nyc. They also perform instrumentation and get coverage information from running the test suite. Especially nice is their mocha integration: if your code is already instrumented you just run `nyc mocha some-test.js` and it 'magically' gets the coverage information without any changes to the tests.
