### ISSUE TITLE
Refactoring to mono-repo.

### ISSUE THREAD

**Issue by urish** [urish/typewiz#54]
Right now, we have a semi mono-repo structure: the core functionality lives in [src](src/), but typewiz-node and typewiz-webpack already live under [packages/](packages/).

I think it will make more sense to go all the way mono-repo - basically moving the core library to live inside 
a [packages](packages/) subdirectory, and setup lerna or a similar tool for simplifying running tests across the repo during development / CI builds.

**Comment by MadaraUchiha** [comment]
I'm actually not too familiar with tools for managing mono repos, could be interesting. The dude behind bit is stationed here in Israel IIRC, maybe we could see about that? (Unless you're more familiar with another tool, I have no preference as I have no experience in the field :D)

**Comment by urish** [comment]
I did some research and found [lerna](https://lernajs.io/) to be quite popular and [feature-packed](http://rachaelmoore.name/posts/development/devops/comparison-of-monorepo-tools/), so I decided to give it a try in #56. So far it seems good!
