### ISSUE TITLE
CLI doesn't work under linux

### ISSUE THREAD

**Issue by zoehneto** [urish/typewiz#62]
Because the typewiz CLI is published with CRLF line endings, it can not be used on linux.

The error message is `/usr/bin/env: 'node\r': No such file or directory`. Manually changing the line endings to LF for the entry file symlinked under `node_modules/.bin/typewiz` fixes this.

This also blocks the PR at urish/typewiz-webpack-demo#1

**Comment by urish** [comment]
Seems similar to #22 - I will look into that shortly and fix

**Comment by urish** [comment]
@zoehneto I just published 1.0.0-beta.2 - can you please check if this fixes the issue for you?

**Comment by zoehneto** [comment]
@urish 1.0.0-beta.2 fixes the issue, I have also updated the PR for `typewiz-webpack-demo` to use it.
