### ISSUE TITLE
Release 1.0.0 🎉

### ISSUE THREAD

**Issue by urish** [urish/typewiz#65]
@zoehneto do you find anything missing or can I merge your PRs and release 1.0.0?

**Comment by zoehneto** [comment]
From my side everything is done, documentation should be complete / up to date and Schema Store is merged. Once you release 1.0.0 I can update the PR for the webpack demo or you merge it and update the dependency in package.json

**Comment by urish** [comment]
Awesome, I'm going to release in the next few hours - will ping you once it's out :)

**Comment by urish** [comment]
Released! 😄
