### ISSUE TITLE
Ideas: Get improved types to existing TS project, Generate d.ts for project

### ISSUE THREAD

**Issue by qballer** [urish/typewiz#74]
I have a couple of ideas (questions ?)

Lets say I have a typescript project which I want to improve it's existing types. Is there a way to run typewiz in a fashion which will output a list of suggestions for better types?  and  I will be able to apply them if I want. 

Lets say I have an existing project and all I want is to generate a d.ts file for it. Typewiz seems like a project which can do that. What do you think?

**Comment by urish** [comment]
Hi @qballer , regarding the first question, see #30, I think it pretty much covers the same request.

Regarding the second question - there is a different project called [dts-gen](https://github.com/Microsoft/dts-gen) that pretty much aims to solve this problem, though I definitely see how the technology used by TypeWiz can help here. If you wish to try and prototype something, I can offer my guidance

**Comment by qballer** [comment]
Sounds really interesting but I lack time to do it. Thanks for you comments.
