### ISSUE TITLE
React & React Native support ?

### ISSUE THREAD

**Issue by Kompwu** [urish/typewiz#79]
I couldn't get it to work, but it would be really cool.

**Comment by urish** [comment]
Are you using webpack with React? Have you tried following the instructions for [typewiz-webpack](https://github.com/urish/typewiz/blob/master/packages/typewiz-webpack/README.md)?

**Comment by Kompwu** [comment]
@urish I'm not.

**Comment by urish** [comment]
So what does your setup look like?

**Comment by Kompwu** [comment]
@urish https://github.com/emin93/react-native-template-typescript

**Comment by Kompwu** [comment]
@urish Any news ?

**Comment by devinrhode2** [comment]
You could try create-react-app, eject, put your code inside the src directory... but you need to at least temporarily migrate to a webpack-based setup.

I'm guessing this is old enough, we can close the issue. Or, update the title. This appears to have nothing to do with react itself

**Comment by urish** [comment]
True
